# Open Project theme setup

title: Ribose Open

tagline: >-
  Open source projects for developers and designers

pitch: >-
  Ribose
  <br>
  open hub

description: >-
  Open source projects for developers and designers

seo:
  type: Organization

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc

legal:
  name: Ribose
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

is_hub: true

permalink: /blog/:month-:day-:year/:title/

theme: jekyll-theme-open-project
