# Open Project theme setup

title: Ribose Open
title_html: Open-source projects for&nbsp;developers and&nbsp;designers

tagline: >-
  <strong>Open-source projects</strong>
  <br>
  for&nbsp;developers and&nbsp;designers

description: >-
  Open source projects for developers and designers

seo:
  type: Organization

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

is_hub: true

permalink: /blog/:month-:day-:year/:title/

theme: jekyll-theme-open-project

url: https://open.ribose.com/

algolia_search:
  api_key: '40a5c3929d2f6d51c9a062d2bdf00c20'
  index_name: 'prod_riboseopen'

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"
