# Open Project theme setup

title: Ribose Open

tagline: >-
  Open source projects for developers and designers

pitch: >-
  Write open hub pitch here.
  <br>
  It will appear on home page hero unit.

description: >-
  Write open hub description, mission, etc. here.
  It will appear in document head meta for search results, and elsewhere.

seo:
  type: Organization

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc


# Required by Open Project theme

markdown: kramdown
theme: jekyll-theme-open-project

includes_dir: .

exclude:
  - '*.yml'
  - 'README.*'
  - 'Gemfile*'
  - 'Jenkinsfile'
  - 'Rakefile'
  - 'ro-site*'

collections:
  projects:
    output: false
  posts:
    output: true
    permalink: /blog/:month-:day-:year/:title/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
