# Open Project theme setup

title: Ribose Open

tagline: >-
  Open source projects for developers and designers

pitch: >-
  Write open hub pitch here.
  <br>
  It will appear on home page hero unit.

description: >-
  Write open hub description, mission, etc. here.
  It will appear in document head meta for search results, and elsewhere.

seo:
  type: Organization

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc

is_hub: true

permalink: /blog/:month-:day-:year/:title/

theme: jekyll-theme-open-project
