name: links

on:
  push:
    branches:
      - main
      - staging
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: ruby/setup-ruby@v1
        with:
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          ruby-version: '3.0'
          bundler-cache: true

      - name: Build site
        run: |
          make _site

      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --no-progress --exclude assets --exclude "file:" --exclude "javascript:" -- _site/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
